#!/usr/bin/env python3

from sys import argv

import plotly as py
import plotly.graph_objs as go
import pandas as pd

# Read massif data from csv format
df = pd.read_csv(argv[1], comment='#')
# print(df.head())

x_axis = df['time']

# Create traces
heapTrace = go.Scatter(x=x_axis,
                       y=df['heap'],  # Data
                       mode='lines+markers',
                       name='heap')   # Additional options
stackTrace = go.Scatter(x=x_axis,
                        y=df['stack'],
                        mode='lines+markers',
                        name='stack')
totalTrace = go.Scatter(x=x_axis,
                        y=df['total'],
                        mode='lines+markers',
                        name='total')

# Plot and embed in ipython notebook!
data = [heapTrace, stackTrace, totalTrace]
py.offline.plot(data, auto_open=False)

