#!/usr/bin/env python3


def fixM(a):
    return [x / 10**6 for x in a]

import plotly as py
import plotly.graph_objs as go
import pandas as pd

# Read massif data from csv format
summary_file = 'test/inputs/mem_summary.csv'
df = pd.read_csv(summary_file, skipinitialspace=True)
# print(df.head())

x_axis = df['#input']

# Create traces
originalTrace = go.Bar(x=x_axis,
                       y=fixM(df['#original']),  # Data
                       name='Original file')   # Additional options
bpTrace = go.Bar(x=x_axis,
                 y=fixM(df['#cjson_bp']),
                 marker={'color': '#FFCA28'},
                 name='Cjson (BP)')
dfTrace = go.Bar(x=x_axis,
                 y=fixM(df['#cjson_df']),
                 name='Cjson (DFUDS)')
pointerBpTrace = go.Bar(x=x_axis,
                        y=fixM(df['#pointer_bp']),
                        marker={'color': '#00897B'},
                        name='Cjson (pointer, BP)')
pointerDfTrace = go.Bar(x=x_axis,
                        y=fixM(df['#pointer_df']),
                        name='Cjson (pointer, DFUDS)')
rapidTrace = go.Bar(x=x_axis,
                    y=fixM(df['#rapid']),
                    marker={'color': '#303F9F'},
                    name='RapidJson')

layout = go.Layout(
    barmode='group',
    autosize=False,
    # width=500, height=500,
    xaxis={'tickangle': -45},
    # xaxis={'title'='SNLI input file'}
    #            range=[.95, 10.05],
    #            tick0=1, dtick=1),
    yaxis={'title': 'RAM usage (MB)', 'dtick': 50}
)

# Assemble traces that will be ploted
# data = [rapidTrace, bpTrace, dfTrace, pointerBpTrace, pointerDfTrace]
data = [rapidTrace, bpTrace, pointerBpTrace]
# Make figure from data and layout
fig = go.Figure(data=data, layout=layout)

# Generate the plot
py.offline.plot(fig, auto_open=True)

